[[vanity]]
import_path = "l7e.io/vanity"
vcs = "git"
vcs_path = "https://github.com/livetribe"
[[vanity]]
import_path = "l7e.io/yama"
vcs = "git"
vcs_path = "https://github.com/livetribe"
[[vanity]]
import_path = "l7e.io/versioning"
vcs = "git"
vcs_path = "https://github.com/livetribe"
[[vanity]]
import_path = "l7e.io/semver"
vcs = "git"
vcs_path = "https://github.com/livetribe"
[[vanity]]
import_path = "l7e.io/lt"
vcs = "git"
vcs_path = "https://github.com/livetribe"
